# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypets',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
