# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0002_auto_20180308_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypets',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
