# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0006_auto_20180329_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypetsimage',
            name='mypets',
        ),
        migrations.AddField(
            model_name='mypets',
            name='photo',
            field=models.FileField(default='', upload_to='photo/'),
        ),
        migrations.DeleteModel(
            name='MypetsImage',
        ),
    ]
