# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0008_auto_20180329_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBattleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='battle/')),
                ('image2', models.ImageField(upload_to='battle/')),
            ],
        ),
        migrations.AlterField(
            model_name='mypetsimage',
            name='mypets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mypet.Mypets'),
        ),
    ]
