# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0011_auto_20180403_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbattleimages',
            name='image1_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='petbattleimages',
            name='image2_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mypetsimage',
            name='mypets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypet.Mypets'),
        ),
    ]
